[package]
name = "multi_net"
version = "0.1.0"
authors = ["Jacob Hughes <j@jacobhughes.me>"]

[dependencies]
tokio-core = "0.1"
futures = "0.1"
net2 = "0.2"
lru-cache = "0.1.1"
byteorder = "1.1"
error-chain = "0.10"
