[package]
name = "vamp-host"
version = "0.1.0"
authors = ["Jacob Hughes <exrook.j@gmail.com>"]
build = "build.rs"

[dependencies]
cpp = "0.2"
cpp_macros = "0.2"

[build-dependencies]
cpp_build = "0.2"
#bindgen = "0.22"
