[package]
name = "set_neopixels"
version = "0.1.0"
authors = ["Jacob Hughes <exrook.j@gmail.com>"]

[dependencies]
serial = "0.3"
clap = { version = "2.23", optional = true }

[[bin]]
name = "set_neopixels"
required-features = ["clap"]
