[package]
name = "led_reciever"
version = "0.1.0"
authors = ["Jacob Hughes <j@jacobhughes.me>"]

[dependencies]
tokio-core = "0.1"
error-chain = "0.11"
clap = "2"
led_control = { path = "../led_control", features = ["serde", "palette-traits"] }
lednet = { path = "../lednet" }
