[package]
name = "send_leds"
version = "0.1.0"
authors = ["Jacob Hughes <j@jacobhughes.me>"]

[dependencies]
led_control = { path = "../led_control" }
clap = "2.23"
lednet = { path = "../lednet" }
error-chain = "0.11"
tokio-core = "0.1"
